### ISSUE TITLE
Design Wireframes

### ISSUE THREAD

**Issue by GJSayers** [GJSayers/calma#4]

**Comment by davidindub** [comment]
![mockup1](https://user-images.githubusercontent.com/69420622/151668669-b666f27e-1f99-44d8-92e4-acd3c66d1092.jpg)
![mockup2](https://user-images.githubusercontent.com/69420622/151668671-ec8d3b94-7106-422e-b1f4-b3dd2ab3c0f1.jpg)
![mockup3](https://user-images.githubusercontent.com/69420622/151668672-c0fcb78d-8269-4913-a916-851563ca30c7.png)
