### ISSUE TITLE
Allauth form styling

### ISSUE THREAD

**Issue by GJSayers** [GJSayers/calma#8]
![Screenshot 2022-01-28 at 09 57 44](https://user-images.githubusercontent.com/72015746/151517411-03a35392-6b05-43a3-be2c-0d57d523bfab.png)

Most important are login / logout / signup

**Comment by davidindub** [comment]
<img width="689" alt="Screenshot 2022-01-30 at 17 46 49" src="https://user-images.githubusercontent.com/69420622/151710946-0e8489a6-c123-417a-b8c5-6e5fb6aafaca.png">
